name: Run tests

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Runs on any open or reopened pull request
  pull_request:
    types: [opened, reopened]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: nicknovitski/nix-develop@v1
      - name: Build project
        run: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release .. && cmake --build .
      - name: Run `pytest`
        run: pytest